### PR TITLE
[CL-86] Document API

### PR DESCRIPTION
**Pull request by guarde**

### CODE REVIEW

**Review by stevelw — CHANGES_REQUESTED** [review]
Waiting for main to catch up

**Review by stevelw — CHANGES_REQUESTED** [review]
Looks like your Insomnia export is missing {{ _.URL }}

**Comment by guarde** [comment]
It imports perfectly fine for me, and I can see the URL variable in the .json! Do you get an error or something?

**Comment by stevelw** [comment]
> It imports perfectly fine for me, and I can see the URL variable in the .json! Do you get an error or something?

It's not appearing in environment variables. I can't see it defined anywhere in the PR version.

To reproduce, have you tried deleting your environment variables and re-importing?

**Comment by guarde** [comment]
> > It imports perfectly fine for me, and I can see the URL variable in the .json! Do you get an error or something?
> 
> It's not appearing in environment variables. I can't see it defined anywhere in the PR version.
> 
> To reproduce, have you tried deleting your environment variables and re-importing?

Just deleted the whole collection, and any environment variables attached and tried re-importing, still worked. I can even see it in the huge mess that is the JSON file

**Comment by guarde** [comment]
> > > It imports perfectly fine for me, and I can see the URL variable in the .json! Do you get an error or something?
> > 
> > 
> > It's not appearing in environment variables. I can't see it defined anywhere in the PR version.
> > To reproduce, have you tried deleting your environment variables and re-importing?
> 
> Just deleted the whole collection, and any environment variables attached and tried re-importing, still worked. I can even see it in the huge mess that is the JSON file

I pulled down the version that's stored here, searched for it in the JSON. Not sure why you can't import it. We should probably see if @PhilTBatt or @mizamidou run into the same issue

image

**Comment by stevelw** [comment]
> Just deleted the whole collection, and any environment variables attached and tried re-importing, still worked. I can even see it in the huge mess that is the JSON file
> 
> I pulled down the version that's stored here, searched for it in the JSON. Not sure why you can't import it. We should probably see if @PhilTBatt or @mizamidou run into the same issue

I just tried deleting the local Insomnia collection and reimporting and it's working now. I must have had some local override somewhere in Insomnia that was screwing it up.

**Review by stevelw — APPROVED** [review]

**Review by PhilTBatt — APPROVED** [review]

**Pull request merged**
